force-app/main/default/objects/Leave_Request__c/Leave_Request__c.object-meta.xml
<CustomObject>
    <description>This object is used in LWC Leave request management application.</description>
    <label>Leave Request</label>
    <nameField>
        <displayFormat>LR-{0000}</displayFormat>
        <label>Leave Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Leave Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Leave_Request__c/fields/From_Date__c.field-meta.xml
<CustomField>
    <fullName>From_Date__c</fullName>
    <label>From Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/Manager_Comment__c.field-meta.xml
<CustomField>
    <fullName>Manager_Comment__c</fullName>
    <label>Manager Comment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/To_Date__c.field-meta.xml
<CustomField>
    <fullName>To_Date__c</fullName>
    <label>To Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Leave_Request__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leave_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LeaveRequestController.cls
public with sharing class LeaveRequestController {
    @AuraEnabled(cacheable=true)
    public static List<Leave_Request__c> getLeave(){
        try{
            List<Leave_Request__c> myLeaves = new List<Leave_Request__c>();
                myLeaves = [select Id, From_Date__c, Name, Manager_Comment__c, Reason__c, Status__c, To_Date__c, User__c, CreatedDate FROM Leave_Request__c WHERE 
                User__c =:UserInfo.getUserId() ORDER BY CreatedDate Desc];
                return myLeaves;
        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }


    @AuraEnabled(cacheable=true)
    public static List<Leave_Request__c> getMyLeave(){
        try{
            List<Leave_Request__c> myLeaves = new List<Leave_Request__c>();
                myLeaves = [select Id, From_Date__c, Name, Manager_Comment__c, Reason__c, Status__c, To_Date__c, CreatedDate, User__r.ManagerId, User__r.Name
                FROM Leave_Request__c WHERE 
                User__r.ManagerId =:UserInfo.getUserId() ORDER BY CreatedDate Desc];
                return myLeaves;
        }
        catch (Exception ex){
            throw new AuraHandledException(ex.getMessage());
        }
    }
}